import { StyleSheet } from "react-native";
const color = {
  primary: "#161621",
  secondary: "#2B2B38",
  active: "#F74346",
  inActive: "#4A4B56",
  text: "#F1F1F1",
  violet: "#4C4F90",
  fadedBg: "#4A4B56",
};
export const style = StyleSheet.create({
  container: {
    backgroundColor: color.primary,
    color: "#fff",
    position: "relative",
    height: "100%",
    paddingTop: 40,
  },
  flexRow: {
    display: "flex",
    flexDirection: "row",
  },
  flexCol: {
    display: "flex",
    flexDirection: "col",
  },
  flexCenter: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  headline: {
    rowGap: 20,
  },
  headlineElements: {
    justifyContent: "space-between",
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  buttonContainer: {
    justifyContent: "flex-end",
    columnGap: 15,
    width: "50%",
  },
  searchButtons: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: color.active,
  },
  promotionCard: {
    justifyContent: "space-around",
    backgroundColor: color.secondary,
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 20,
  },
  promoText: {
    color: color.text,
    fontSize: 18,
    display: "flex",
    flexWrap: "wrap",
  },
  promoTextBold: {
    color: color.text,
    fontSize: 24,
    display: "flex",
    flexWrap: "wrap",
    fontWeight: "bold",
  },
  promoCardArrow: {
    width: 60,
    height: 60,
    borderRadius: 15,
    backgroundColor: color.active,
  },
  navigateContainer: {
    columnGap: 10,
    paddingHorizontal: 25,
  },
  navigateText: {
    padding: 20,
    paddingVertical: 16,
    borderStyle: "solid",
    borderWidth: 2,
    borderRadius: 20,
    borderColor: color.secondary,
    width: "50%",
    textAlign: "center",
    backgroundColor: color.secondary,
    fontSize: 20,
    color: color.text,
  },
  navigateTextActive: {
    borderColor: color.active,
    color: color.active,
    fontWeight: "bold",
  },
  movieCard: {
    marginHorizontal: 15,
    height: 420,
  },
  movieTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#F74346",
  },
  movieSubTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: color.active,
  },
  movieContainer: {
    paddingHorizontal: 10,
    padding: 0,
  },
  navigation: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "8%",
  },
  activeButtons: {
    borderBottomColor: color.active,
    borderBottomWidth: 2,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    paddingBottom: 8,
  },
  inActiveButtons: {
    borderBottomColor: color.primary,
    borderBottomWidth: 2,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    paddingBottom: 8,
  },
  activeText: {
    color: color.active,
  },
  inActiveText: {
    color: color.inActive,
  },
  rotateIcon: {
    transform: [{ rotate: "180deg" }],
    width: 50,
    marginLeft: 20,
    paddingRight: 7,
  },
  /* Movie Detail Style */
  mdTrailerContainer: {
    position: "relative",
    backgroundColor: "green",
    height: "40%",
  },
  mdMovieImage: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  viewTrailer: {
    position: "absolute",
    bottom: 0,
    right: 40,
    columnGap: 10,
    width: 160,
    paddingVertical: 15,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    borderRadius: 20,
  },
  trailerPlayIcon: {
    backgroundColor: color.text,
    borderRadius: 30,
    color: color.active,
    display: "flex",
    justifyContent: "center",
    padding: 8,
    paddingLeft: 10,
  },
  trailerText: {
    color: color.text,
    fontSize: 24,
  },
  mdDetailContainer: {
    paddingTop: 18,
  },
  genereContainer: {
    marginTop: 30,
  },
  genere: {
    color: color.text,
    backgroundColor: color.secondary,
    paddingHorizontal: 20,
    paddingVertical: 7,
    borderRadius: 30,
    marginHorizontal: 8,
  },
  actorsAvatar: {
    width: 70,
    height: 70,
    borderRadius: 30,
    marginHorizontal: 5,
  },
  movieDescription: {
    color: color.text,
    fontSize: 16,
    textAlign: "center",
    paddingHorizontal: 30,
    marginTop: 30,
  },
  booking: {
    width: "60%",
    marginHorizontal: "20%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    columnGap: 50,
    marginTop: 25,
    borderRadius: 17,
  },
  /* Select Date */
  sdHeader: {
    columnGap: 10,
  },
  sdText: {
    color: color.text,
    fontSize: 28,
    fontWeight: "bold",
    paddingLeft: 35,
    paddingTop: 8,
    flexGrow: 1,
  },
  seatContainer: {
    columnGap: 25,
  },
  avBox: {
    height: 25,
    borderWidth: 2.5,
    borderColor: color.active,
    borderRadius: 6,
    flexBasis: "20%",
  },
  sdBox: {
    backgroundColor: color.active,
  },
  rsBox: {
    borderColor: color.violet,
    backgroundColor: color.violet,
  },
  seatFlex: {
    padding: 4,
    justifyContent: "space-around",
    flexWrap: "wrap",
    gap: 8,
    flexBasis: "45%",
  },
  movieScreen: {
    height: 20,
    backgroundColor: color.violet,
    width: "100%",
    borderRadius: 10,
    shadowColor: color.violet,
    shadowOffset: { width: 30, height: 30 },
    shadowOpacity: 30,
    shadowRadius: 0,
    elevation: 30,
  },
  movieScreenText: {
    color: color.text,
    textAlign: "center",
    fontSize: 13,
  },
  tableIndicatorTab: {
    justifyContent: "space-around",
  },
  tableIndicatorBox: {
    width: 20,
    height: 20,
    backgroundColor: color.active,
    borderRadius: 4,
    marginRight: 10,
  },
  tableIndicatorSd: {
    backgroundColor: color.active,
  },
  tableIndicatorRs: {
    backgroundColor: color.violet,
  },
  tableIndicatorAv: {
    backgroundColor: null,
    borderWidth: 2,
    borderColor: color.active,
  },
  tableIndicator: {
    color: color.text,
  },
  sdCard: {
    backgroundColor: color.secondary,
    padding: 20,
    borderRadius: 20,
    marginHorizontal: 20,
    marginVertical: 10,
    rowGap: 20,
  },
  seletDay: {
    textAlign: "center",
    color: color.text,
    fontSize: 20,
    fontWeight: "bold",
  },
  dayContainer: {
    columnGap: 10,
  },
  dayCard: {
    flexGrow: 1,
    backgroundColor: color.fadedBg,
    padding: 7,
    borderRadius: 15,
  },
  activeDate: {
    backgroundColor: color.active,
  },
  monthText: {
    color: color.text,
    fontSize: 12,
  },
  dayText: {
    color: color.text,
    fontSize: 16,
    fontWeight: "bold",
  },
  timeText: {
    backgroundColor: color.active,
    textAlign: "center",
    color: color.text,
    width: "30%",
    padding: 7,
    borderRadius: 20,
    marginHorizontal: "35%",
  },
  checkout: {
    columnGap: 30,
  },
  checkoutText: {
    fontSize: 24,
    color: color.text,
    fontWeight: "bold",
  },
  /* Checkout */
  checkoutImageContainer: {
    padding: 20,
  },
  checkoutImage: {
    width: 150,
    height: 200,
    borderRadius: 15,
  },
  checkoutTextContainer: {
    justifyContent: "center",
    paddingLeft: 20,
    rowGap: 10,
  },
  checkoutMovieTitle: {
    color: color.text,
    fontSize: 30,
    fontWeight: "bold",
    display: "flex",
    width: 180,
    flexWrap: "wrap",
  },
  checkoutGenerText: {
    color: color.fadedBg,
    fontWeight: "bold",
  },
  checkoutMoiveLocation: {
    color: color.text,
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "row",
    alignItems: "center",
  },
  checkoutLocationText: {
    color: color.text,
  },
  payListContainer: {
    rowGap: 20,
    paddingTop: 20,
  },
  payCard: {
    marginHorizontal: 25,
    paddingBottom: 18,
    justifyContent: "space-between",
    borderBottomWidth: 2,
    borderBottomColor: color.secondary,
  },
  textIconContainer: {
    justifyContent: "space-around",
    columnGap: 40,
    alignItems: "center",
  },
  payText: {
    color: color.fadedBg,
    fontSize: 22,
  },
  payCheckBox: {
    borderWidth: 3,
    padding: 5,
    width: 35,
    height: 35,
    borderRadius: 8,
    borderColor: color.violet,
  },
});
